# Generated by Django 2.2.7 on 2020-12-22 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyeeDetails',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=200)),
                ('com_email', models.EmailField(max_length=254)),
                ('com_logo', models.ImageField(upload_to='media/')),
                ('com_city', models.CharField(max_length=200)),
                ('com_address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=200)),
                ('exprience', models.CharField(max_length=300)),
                ('edication', models.CharField(max_length=400)),
                ('job_type', models.CharField(max_length=200)),
                ('schedule', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('dicription', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.CompanyeeDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
